import { createApp } from "vue";
import { createStore } from "vuex";

const store = createStore({
  state() {
    return {
      allAnime: [
        {
          id: 0,
          img: "5premium-card.png",
          title: "Мэйджор. Мяч дружбы / 2002 ",
          type: "anime serial",
          viewer: 323232,
          about:
            " About 1-card Gol D. Rojer 'Qaroqchilar qiroli' sifatida tanilgan bo'lib, Grand Lineda suzib o'tgan eng kuchli va eng obro'li mavjudot. Rojerning Jahon hukumati tomonidan qo'lga olinishi va qatl etilishi butun dunyoda o'zgarishlarga olib keldi. Uning o'limidan oldingi so'nggi so'zlari dunyodagi eng katta xazina - One Piece mavjudligini ochib berdi. Aynan shu vahiy cheksiz boylik va shon-shuhratni va'da qiladigan One Piece-ni va ehtimol shon-shuhrat cho'qqisini va Pirat Qiroli unvonini topishni orzu qilgan qaroqchilarning Buyuk Asrini keltirib chiqardi.",
          video: "youName.mp4",
          dateTime: 2023,
          genre: "Kundalik Hayot, Maktab",
          language: "O'zbek",
          duration: "24 minut",
          images: [
            "kadr-1.png",
            "kadr-2.png",
            "kadr-3.png",
            "kadr-4.png",
            "kadr-5.png",
            "kadr-6.png",
          ],
        },
        {
          id: 1,
          img: "6premium-card.png",
          title: "Мэйджор. Мяч дружбы / 2008 ",
          type: "anime serial",
          viewer: 323232,
          about:
            "About 2-card Gol D. Rojer 'Qaroqchilar qiroli' sifatida tanilgan bo'lib, Grand Lineda suzib o'tgan eng kuchli va eng obro'li mavjudot. Rojerning Jahon hukumati tomonidan qo'lga olinishi va qatl etilishi butun dunyoda o'zgarishlarga olib keldi. Uning o'limidan oldingi so'nggi so'zlari dunyodagi eng katta xazina - One Piece mavjudligini ochib berdi. Aynan shu vahiy cheksiz boylik va shon-shuhratni va'da qiladigan One Piece-ni va ehtimol shon-shuhrat cho'qqisini va Pirat Qiroli unvonini topishni orzu qilgan qaroqchilarning Buyuk Asrini keltirib chiqardi.",
          video: "youName.mp4",
          dateTime: 2023,
          genre: "Sehir, Jangari",
          language: "O'zbek",
          duration: "24 minut",
          images: [
            "kadr-1.png",
            "kadr-2.png",
            "kadr-3.png",
            "kadr-4.png",
            "kadr-5.png",
            "kadr-6.png",
          ],
        },
        {
          id: 2,
          img: "7premium-card.png",
          title: "Мэйджор. Мяч дружбы / 2008 ",
          type: "anime serial",
          viewer: 323232,
          about:
            "Gol D. Rojer 'Qaroqchilar qiroli' sifatida tanilgan bo'lib, Grand Lineda suzib o'tgan eng kuchli va eng obro'li mavjudot. Rojerning Jahon hukumati tomonidan qo'lga olinishi va qatl etilishi butun dunyoda o'zgarishlarga olib keldi. Uning o'limidan oldingi so'nggi so'zlari dunyodagi eng katta xazina - One Piece mavjudligini ochib berdi. Aynan shu vahiy cheksiz boylik va shon-shuhratni va'da qiladigan One Piece-ni va ehtimol shon-shuhrat cho'qqisini va Pirat Qiroli unvonini topishni orzu qilgan qaroqchilarning Buyuk Asrini keltirib chiqardi.",
          video: "youName.mp4",
          dateTime: 2023,
          genre: "Sehir, Jangari",
          language: "O'zbek",
          duration: "24 minut",
          images: [
            "kadr-1.png",
            "kadr-2.png",
            "kadr-3.png",
            "kadr-4.png",
            "kadr-5.png",
            "kadr-6.png",
          ],
        },
        {
          id: 3,
          img: "8premium-card.png",
          title: "Мэйджор. Мяч дружбы / 2008 ",
          type: "anime serial",
          viewer: 323232,
          about:
            "Gol D. Rojer 'Qaroqchilar qiroli' sifatida tanilgan bo'lib, Grand Lineda suzib o'tgan eng kuchli va eng obro'li mavjudot. Rojerning Jahon hukumati tomonidan qo'lga olinishi va qatl etilishi butun dunyoda o'zgarishlarga olib keldi. Uning o'limidan oldingi so'nggi so'zlari dunyodagi eng katta xazina - One Piece mavjudligini ochib berdi. Aynan shu vahiy cheksiz boylik va shon-shuhratni va'da qiladigan One Piece-ni va ehtimol shon-shuhrat cho'qqisini va Pirat Qiroli unvonini topishni orzu qilgan qaroqchilarning Buyuk Asrini keltirib chiqardi.",
          video: "youName.mp4",
          dateTime: 2023,
          genre: "Sehir, Jangari",
          language: "O'zbek",
          duration: "24 minut",
          images: [
            "kadr-1.png",
            "kadr-2.png",
            "kadr-3.png",
            "kadr-4.png",
            "kadr-5.png",
            "kadr-6.png",
          ],
        },
        {
          id: 4,
          img: "9premium-card.png",
          title: "Мэйджор. Мяч дружбы / 2008 ",
          type: "anime serial",
          viewer: 323232,
          about:
            "Gol D. Rojer 'Qaroqchilar qiroli' sifatida tanilgan bo'lib, Grand Lineda suzib o'tgan eng kuchli va eng obro'li mavjudot. Rojerning Jahon hukumati tomonidan qo'lga olinishi va qatl etilishi butun dunyoda o'zgarishlarga olib keldi. Uning o'limidan oldingi so'nggi so'zlari dunyodagi eng katta xazina - One Piece mavjudligini ochib berdi. Aynan shu vahiy cheksiz boylik va shon-shuhratni va'da qiladigan One Piece-ni va ehtimol shon-shuhrat cho'qqisini va Pirat Qiroli unvonini topishni orzu qilgan qaroqchilarning Buyuk Asrini keltirib chiqardi.",
          video: "youName.mp4",
          dateTime: 2023,
          genre: "Sehir, Jangari",
          language: "O'zbek",
          duration: "24 minut",
          images: [
            "kadr-1.png",
            "kadr-2.png",
            "kadr-3.png",
            "kadr-4.png",
            "kadr-5.png",
            "kadr-6.png",
          ],
        },
        {
          id: 5,
          img: "10premium-card.png",
          title: "Мэйджор. Мяч дружбы / 2008 ",
          type: "anime serial",
          viewer: 323232,
          about:
            "Gol D. Rojer 'Qaroqchilar qiroli' sifatida tanilgan bo'lib, Grand Lineda suzib o'tgan eng kuchli va eng obro'li mavjudot. Rojerning Jahon hukumati tomonidan qo'lga olinishi va qatl etilishi butun dunyoda o'zgarishlarga olib keldi. Uning o'limidan oldingi so'nggi so'zlari dunyodagi eng katta xazina - One Piece mavjudligini ochib berdi. Aynan shu vahiy cheksiz boylik va shon-shuhratni va'da qiladigan One Piece-ni va ehtimol shon-shuhrat cho'qqisini va Pirat Qiroli unvonini topishni orzu qilgan qaroqchilarning Buyuk Asrini keltirib chiqardi.",
          video: "youName.mp4",
          dateTime: 2023,
          genre: "Sehir, Jangari",
          language: "O'zbek",
          duration: "24 minut",
          images: [
            "kadr-1.png",
            "kadr-2.png",
            "kadr-3.png",
            "kadr-4.png",
            "kadr-5.png",
            "kadr-6.png",
          ],
        },
        {
          id: 6,
          img: "10premium-card.png",
          title: "Мэйджор. Мяч дружбы / 2008 ",
          type: "anime serial",
          viewer: 323232,
          about:
            "Gol D. Rojer 'Qaroqchilar qiroli' sifatida tanilgan bo'lib, Grand Lineda suzib o'tgan eng kuchli va eng obro'li mavjudot. Rojerning Jahon hukumati tomonidan qo'lga olinishi va qatl etilishi butun dunyoda o'zgarishlarga olib keldi. Uning o'limidan oldingi so'nggi so'zlari dunyodagi eng katta xazina - One Piece mavjudligini ochib berdi. Aynan shu vahiy cheksiz boylik va shon-shuhratni va'da qiladigan One Piece-ni va ehtimol shon-shuhrat cho'qqisini va Pirat Qiroli unvonini topishni orzu qilgan qaroqchilarning Buyuk Asrini keltirib chiqardi.",
          video: "youName.mp4",
          dateTime: 2023,
          genre: "Sehir, Jangari",
          language: "O'zbek",
          duration: "24 minut",
          images: [
            "kadr-1.png",
            "kadr-2.png",
            "kadr-3.png",
            "kadr-4.png",
            "kadr-5.png",
            "kadr-6.png",
          ],
        },
        {
          id: 7,
          img: "11premium-card.png",
          title: "Мэйджор. Мяч дружбы / 2008 ",
          type: "anime serial",
          viewer: 323232,
          about:
            "Gol D. Rojer 'Qaroqchilar qiroli' sifatida tanilgan bo'lib, Grand Lineda suzib o'tgan eng kuchli va eng obro'li mavjudot. Rojerning Jahon hukumati tomonidan qo'lga olinishi va qatl etilishi butun dunyoda o'zgarishlarga olib keldi. Uning o'limidan oldingi so'nggi so'zlari dunyodagi eng katta xazina - One Piece mavjudligini ochib berdi. Aynan shu vahiy cheksiz boylik va shon-shuhratni va'da qiladigan One Piece-ni va ehtimol shon-shuhrat cho'qqisini va Pirat Qiroli unvonini topishni orzu qilgan qaroqchilarning Buyuk Asrini keltirib chiqardi.",
          video: "youName.mp4",
          dateTime: 2023,
          genre: "Sehir, Jangari",
          language: "O'zbek",
          duration: "24 minut",
          images: [
            "kadr-1.png",
            "kadr-2.png",
            "kadr-3.png",
            "kadr-4.png",
            "kadr-5.png",
            "kadr-6.png",
          ],
        },
        {
          id: 8,
          img: "12premium-card.png",
          title: "Мэйджор. Мяч дружбы / 2008 ",
          type: "anime serial",
          viewer: 323232,
          about:
            "Gol D. Rojer 'Qaroqchilar qiroli' sifatida tanilgan bo'lib, Grand Lineda suzib o'tgan eng kuchli va eng obro'li mavjudot. Rojerning Jahon hukumati tomonidan qo'lga olinishi va qatl etilishi butun dunyoda o'zgarishlarga olib keldi. Uning o'limidan oldingi so'nggi so'zlari dunyodagi eng katta xazina - One Piece mavjudligini ochib berdi. Aynan shu vahiy cheksiz boylik va shon-shuhratni va'da qiladigan One Piece-ni va ehtimol shon-shuhrat cho'qqisini va Pirat Qiroli unvonini topishni orzu qilgan qaroqchilarning Buyuk Asrini keltirib chiqardi.",
          video: "youName.mp4",
          dateTime: 2023,
          genre: "Sehir, Jangari",
          language: "O'zbek",
          duration: "24 minut",
          images: [
            "kadr-1.png",
            "kadr-2.png",
            "kadr-3.png",
            "kadr-4.png",
            "kadr-5.png",
            "kadr-6.png",
          ],
        },
        {
          id: 9,
          img: "13premium-card.png",
          title: "Мэйджор. Мяч дружбы / 2008 ",
          type: "anime serial",
          viewer: 323232,
          about:
            "Gol D. Rojer 'Qaroqchilar qiroli' sifatida tanilgan bo'lib, Grand Lineda suzib o'tgan eng kuchli va eng obro'li mavjudot. Rojerning Jahon hukumati tomonidan qo'lga olinishi va qatl etilishi butun dunyoda o'zgarishlarga olib keldi. Uning o'limidan oldingi so'nggi so'zlari dunyodagi eng katta xazina - One Piece mavjudligini ochib berdi. Aynan shu vahiy cheksiz boylik va shon-shuhratni va'da qiladigan One Piece-ni va ehtimol shon-shuhrat cho'qqisini va Pirat Qiroli unvonini topishni orzu qilgan qaroqchilarning Buyuk Asrini keltirib chiqardi.",
          video: "youName.mp4",
          dateTime: 2023,
          genre: "Sehir, Jangari",
          language: "O'zbek",
          duration: "24 minut",
          images: [
            "kadr-1.png",
            "kadr-2.png",
            "kadr-3.png",
            "kadr-4.png",
            "kadr-5.png",
            "kadr-6.png",
          ],
        },
        {
          id: 10,
          img: "14premium-card.png",
          title: "Мэйджор. Мяч дружбы / 2008 ",
          type: "anime serial",
          viewer: 323232,
          about:
            "Gol D. Rojer 'Qaroqchilar qiroli' sifatida tanilgan bo'lib, Grand Lineda suzib o'tgan eng kuchli va eng obro'li mavjudot. Rojerning Jahon hukumati tomonidan qo'lga olinishi va qatl etilishi butun dunyoda o'zgarishlarga olib keldi. Uning o'limidan oldingi so'nggi so'zlari dunyodagi eng katta xazina - One Piece mavjudligini ochib berdi. Aynan shu vahiy cheksiz boylik va shon-shuhratni va'da qiladigan One Piece-ni va ehtimol shon-shuhrat cho'qqisini va Pirat Qiroli unvonini topishni orzu qilgan qaroqchilarning Buyuk Asrini keltirib chiqardi.",
          video: "youName.mp4",
          dateTime: 2023,
          genre: "Sehir, Jangari",
          language: "O'zbek",
          duration: "24 minut",
          images: [
            "kadr-1.png",
            "kadr-2.png",
            "kadr-3.png",
            "kadr-4.png",
            "kadr-5.png",
            "kadr-6.png",
          ],
        },
        {
          id: 11,
          img: "15premium-card.png",
          title: "Мэйджор. Мяч дружбы / 2008 ",
          type: "anime serial",
          viewer: 323232,
          about:
            "Gol D. Rojer 'Qaroqchilar qiroli' sifatida tanilgan bo'lib, Grand Lineda suzib o'tgan eng kuchli va eng obro'li mavjudot. Rojerning Jahon hukumati tomonidan qo'lga olinishi va qatl etilishi butun dunyoda o'zgarishlarga olib keldi. Uning o'limidan oldingi so'nggi so'zlari dunyodagi eng katta xazina - One Piece mavjudligini ochib berdi. Aynan shu vahiy cheksiz boylik va shon-shuhratni va'da qiladigan One Piece-ni va ehtimol shon-shuhrat cho'qqisini va Pirat Qiroli unvonini topishni orzu qilgan qaroqchilarning Buyuk Asrini keltirib chiqardi.",
          video: "youName.mp4",
          dateTime: 2023,
          genre: "Sehir, Jangari",
          language: "O'zbek",
          duration: "24 minut",
          images: [
            "kadr-1.png",
            "kadr-2.png",
            "kadr-3.png",
            "kadr-4.png",
            "kadr-5.png",
            "kadr-6.png",
          ],
        },
      ],
      anime: [],
      showMoreAnime: [10, 2, 3, 4, 5, 6,],
      rankAnime: [1, 2, 3, 4, 5, 6,],
      movieAnime: [1, 2, 3, 4, 5, 6,],
    };
  },
  mutations: {
    findAnime(state, id) {
      state.anime = state.allAnime.find(a => a.id == id);
    },
  },
});

export default store;
